name: Application Processing

on:
  push:
    branches:
      - main  # Replace with your main branch name
      - master  # Add any other branches you want to trigger the workflow on
  schedule:
    - cron: '0 * * * *'  # Runs every hour

jobs:
  process_applications:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Replace with your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Create directories (if not exist)
        run: |
          mkdir -p successful
          mkdir -p unsuccessful

      - name: Run Python script
        run: python process_applications.py
